import type { Metadata } from "next";
import { DrillRunwayCheck } from "@/components/drill-runway-check/drill-runway-check";
import { DrillWaveACert } from "@/components/drill-wave-a-cert/drill-wave-a-cert";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">{children}<DrillRunwayCheck /><DrillWaveACert /></body>
    </html>
  );
}
